export const TOPIC_CHART_BOX_CLICK = 'TOPIC_CHART_BOX_CLICK'
export const MORE_INFO_CLICK = 'MORE_INFO_CLICK'
export const TOPIC_CHART_SPORT_BOX_CLICK = 'TOPIC_CHART_SPORT_BOX_CLICK'
export const TOPIC_PUSH_ADD_SOMETHING_CLICK = 'TOPIC_PUSH_ADD_SOMETHING_CLICK'
export const TOPIC_HOME_MEMBER_INVITATION_CLICK = 'TOPIC_HOME_MEMBER_INVITATION_CLICK'

