import {createAction} from 'redux-actions'

// 加载数据
export const ATTENTION_MEMBER_PAGE_LOAD_DATA_REQUEST = Symbol('ATTENTION_MEMBER_PAGE_LOAD_DATA_REQUEST')
const loadData = createAction(ATTENTION_MEMBER_PAGE_LOAD_DATA_REQUEST)

export const ATTENTION_MEMBER_PAGE_LOAD_DATA_SUCCESS = Symbol('ATTENTION_MEMBER_PAGE_LOAD_DATA_SUCCESS')
export const loadDataSuccess = createAction(ATTENTION_MEMBER_PAGE_LOAD_DATA_SUCCESS)

// 修改备注
export const ATTENTION_MEMBER_PAGE_UPDATE_REMARK_REQUEST = Symbol('ATTENTION_MEMBER_PAGE_UPDATE_REMARK_REQUEST')
const updateSubscriberRemark = createAction(ATTENTION_MEMBER_PAGE_UPDATE_REMARK_REQUEST)

export const ATTENTION_MEMBER_PAGE_UPDATE_REMARK_SUCCESS = Symbol('ATTENTION_MEMBER_PAGE_UPDATE_REMARK_SUCCESS')
export const updateRemarkSuccess = createAction(ATTENTION_MEMBER_PAGE_UPDATE_REMARK_SUCCESS)

// 取消关注成员
export const ATTENTION_MEMBER_PAGE_UNSUBSERIBE_SUBSCRIBER_REQUEST = Symbol('ATTENTION_MEMBER_PAGE_UNSUBSERIBE_SUBSCRIBER_REQUEST')
const unsubseribeSubscriber = createAction(ATTENTION_MEMBER_PAGE_UNSUBSERIBE_SUBSCRIBER_REQUEST)

export const ATTENTION_MEMBER_PAGE_UNSUBSERIBE_SUBSCRIBER_SUCCESS = Symbol('ATTENTION_MEMBER_PAGE_UNSUBSERIBE_SUBSCRIBER_SUCCESS')
export const unsubseribeSubscriberSuccess = createAction(ATTENTION_MEMBER_PAGE_UNSUBSERIBE_SUBSCRIBER_SUCCESS)

export default {
  loadData,
  updateSubscriberRemark,
  unsubseribeSubscriber,
}
